#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$MDMP_USER" PASSWORD '$MDMP_PASSWORD' LOGIN NOSUPERUSER INHERIT NOREPLICATION;
    CREATE DATABASE "$MDMP_DB";
    GRANT CONNECT ON DATABASE "$MDMP_DB" TO "$MDMP_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$MDMP_DB" <<-EOSQL
        CREATE SCHEMA "$MDMP_SCHEMA" AUTHORIZATION "$MDMP_USER";

EOSQL
