kind: Deployment
apiVersion: apps/v1
metadata:
  name: innerservice-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: innerservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: innerservice
    spec:
      containers:
        - name: innerservice
          image: 'aleshawork/innerservice:1.3'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/sayOk
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1