kind: Deployment
apiVersion: apps/v1
metadata:
  name: myservice
  labels:
    app: myservice
    type: application
    version: 1.1.1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myservice
  strategy:
    type: RollingUpdate
  containers:
    - name: myservice
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      image:
      imagePullPolicy: Always
      livenessProbe:
        httpGet:
          path: /health/sayOk
          port: 8080
          scheme: HTTP
        initialDelaySecond: 0
        periodSecond: 4
        successThreshold: 1