kind: Deployment
apiVersion: apps/v1
metadata:
  name: myservice
  labels:
    app: myservice
    type: application
    version: 1.1.1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myservice
  strategy:
    type: RollingUpdate