kind: Deployment
apiVersion: apps/v1
metadata:
  name: myservice-deployment
  labels:
    app: myservice
    type: application
    version: 1.1.1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - name: myservice
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: 'aleshawork/myservice:1.2'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/sayOk
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 4
            successThreshold: 1