kind: Service
apiVersion: v1
metadata:
  name: myservice-service
  labels:
    app: myservice-service

spec:
  selector:
    app: myservice
  ports:
    - port: 9000
      targetPort: 8080
  type: LoadBalancer